name: esa-phisatnet
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.12.8 #3.9.19
  - pyyaml
  - matplotlib
  - numpy
  - pandas
  - pytorch::pytorch=2.4.0
  - pytorch::torchvision=0.19.0
  - pytorch::torchaudio=2.4.0
  - nvidia::cuda=12.1 # Modify as needed
  - torchinfo
  - tabulate
  - python-lmdb
  - tqdm
  - scipy
  - zarr
  - conda-forge::gdal
  - timm
  - pytorch-lightning
  - scikit-multilearn
  - pip
  - pip:
      - buteo
      - fvcore
