experiment_name: uniphi_downstream/lc_nshot5000_frozen
downstream_task: lc
model_name: phileo_precursor
augmentations: true
batch_size: 16
model_device: cuda
generator_device: cuda
num_workers: 16
early_stop: 15
epochs: 200
input_channels: 10
output_channels: 11
input_size: 128
lr: 0.0001
lr_scheduler: reduce_on_plateau
n_shot: 5000
split_ratio: null
regions: null
vis_val: true
warmup: true
warmup_steps: 5
warmup_gamma: 10
min_lr: null
pretrained_model_path: /lustre/projects/1001/gdaga/home/pretrained_weights/phileo_precursor.ckpt
freeze_pretrained: true
data_path_128_10m: /lustre/projects/1001/gdaga/home/phileo-bench_lc.zarr
data_path_224_10m: /lustre/projects/1001/gdaga/home/phileo-bench_lc.zarr
data_path_224_30m: /lustre/projects/1001/gdaga/home/phileo-bench_lc.zarr
train_mode: train_test
downstream_model_path: null
data_path_inference_128: /lustre/projects/1001/gdaga/home/phileo-bench_lc.zarr
data_path_inference_224: /lustre/projects/1001/gdaga/home/phileo-bench_lc.zarr
output_path: /lustre/projects/1001/gdaga/home/phi2FM_models
data_parallel: false
device_ids:
- 0
pad_bands: 10
only_get_datasets: false
wandb: true
patch_size: 128
shrink_val_set: 0.1
