
experiment_name: nshot_phi2/phi2_gassl
downstream_task: lc
model_name: gassl
augmentations: True
batch_size: 1
model_device: cuda
generator_device: cuda
num_workers: 16
early_stop: 15
epochs: 200
input_channels: 3
output_channels: 11
input_size: 224
lr: 0.0001
lr_scheduler: reduce_on_plateau
n_shot: 0
split_ratio: null
regions: null
vis_val: True
warmup: True
warmp_steps: 5
warmup_gamma: 10
min_lr: null
pretrained_model_path: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/pretrained_weights/moco_geo+tp.pth.tar
freeze_pretrained: True
data_path_128_10m: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/phileo-bench/np_patches_128/
data_path_224_10m: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/phileo-bench/np_patches_224/
data_path_224_30m: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/phileo-bench/np_patches_224/
train_mode: train_test                      # train_test, train_test_inference, inference, train_inference
downstream_model_path: null
data_path_inference_128: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/phileo-bench/np_patches_224/
data_path_inference_224: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/phileo-bench/np_patches_224/
output_path: /home/phimultigpu/phisat2_foundation/models_phileobench
data_parallel: False
device_ids: [1]
pad_bands: 3 # 10 for all models, None for phisatnet, 13 for moco and dino, 3 for gassl
only_get_datasets: False
