
experiment_name: nshot_phi2/phi2_phileo_precursor
downstream_task: lc
model_name: phileo_precursor
augmentations: True
batch_size: 64
model_device: cuda
generator_device: cuda
num_workers: 16
early_stop: 15
epochs: 500
input_channels: 10
output_channels: 11
input_size: 64
lr: 0.0001
lr_scheduler: reduce_on_plateau
n_shot: 0
split_ratio: null
regions: null
vis_val: True
warmup: True
warmp_steps: 5
warmup_gamma: 10
min_lr: null
pretrained_model_path: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/pretrained_weights/phileo-precursor_v09_e013.pt # **********************************
freeze_pretrained: True
data_path_128_10m: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/phileo-bench/np_patches_128/
data_path_224_10m: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/phileo-bench/np_patches_128/
data_path_224_30m: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/phileo-bench/np_patches_128/
train_mode: train_test                      # train_test, train_test_inference, inference, train_inference
downstream_model_path: null
data_path_inference_128: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/phileo-bench/np_patches_128/
data_path_inference_224: /home/phimultigpu/phileo_NFS/phileo_data/phisat2_fm/phileo-bench/np_patches_128/
output_path: /home/phimultigpu/phisat2_foundation/models_phileobench
data_parallel: DDP
device_ids: [0, 1, 2, 3]
pad_bands: 10 # 10 for all models, None for phisatnet, 13 for moco and dino
only_get_datasets: False
