
experiment_name: nshot_phi2/phi2_moco
downstream_task: lc
model_name: moco
augmentations: True
batch_size: 64
model_device: cuda
generator_device: cuda
num_workers: 16
early_stop: 15
epochs: 200
input_channels: 13
output_channels: 11
input_size: 224
lr: 0.0001
lr_scheduler: reduce_on_plateau
n_shot: 0
split_ratio: null
regions: null
vis_val: True
warmup: True
warmp_steps: 5
warmup_gamma: 10
min_lr: null
pretrained_model_path: /home/phisat2/phisat2_foundation/phisat2_fm/pretrained_weights/B13_rn50_moco_0099.pth
freeze_pretrained: True
data_path_128_10m: /home/phisat2/phisat2_foundation/phisat2_fm/phileo-bench/np_patches_128/
data_path_224_10m: /home/phisat2/phisat2_foundation/phisat2_fm/phileo-bench/np_patches_224/
data_path_224_30m: /home/phisat2/phisat2_foundation/phisat2_fm/phileo-bench/np_patches_224/
train_mode: train_test                      # train_test, train_test_inference, inference, train_inference
downstream_model_path: null
data_path_inference_128: /home/phisat2/phisat2_foundation/phisat2_fm/phileo-bench/np_patches_128/
data_path_inference_224: /home/phisat2/phisat2_foundation/phisat2_fm/phileo-bench/np_patches_224/
output_path: /home/phisat2/models
data_parallel: False
device_ids: [0]
pad_bands: 10 # 10 for all models, None for phisatnet, 13 for moco and dino
only_get_datasets: False
