experiment_name: phi2_geoaware/building_nshot1000_frozen
downstream_task: building
model_name: GeoAware_mh_pred_core_nano
augmentations: true
batch_size: 32
model_device: cuda
generator_device: cuda
num_workers: 16
early_stop: 15
epochs: 200
input_channels: 13
output_channels: 1
input_size: 224
lr: 0.0001
lr_scheduler: reduce_on_plateau
n_shot: 1000
split_ratio: null
regions: null
vis_val: true
warmup: true
warmup_steps: 5
warmup_gamma: 10
min_lr: null
pretrained_model_path: /lustre/projects/1001/gdaga/home/pretrained_weights/GeoAware_mh_pred_core_nano_2000ep_s2_rn50.pth
freeze_pretrained: true
data_path_128_10m: /lustre/projects/1001/gdaga/home/phileo-bench_building.zarr
data_path_224_10m: /lustre/projects/1001/gdaga/home/phileo-bench_building.zarr
data_path_224_30m: /lustre/projects/1001/gdaga/home/phileo-bench_building.zarr
train_mode: train_test
downstream_model_path: null
data_path_inference_128: /lustre/projects/1001/gdaga/home/phileo-bench_building.zarr
data_path_inference_224: /lustre/projects/1001/gdaga/home/phileo-bench_building.zarr
output_path: /lustre/projects/1001/gdaga/home/phi2FM_models
data_parallel: false
device_ids:
- 0
pad_bands: 13
only_get_datasets: false
patch_size: 224
