experiment_name: phi2_terramind/roads_nshot1000_frozen
downstream_task: roads_classification
model_name: terramind_segmenter
augmentations: true
batch_size: 48
model_device: mps
generator_device: mps
num_workers: 16
early_stop: 15
epochs: 200
input_channels: 13
output_channels: 2
input_size: 224
patch_size: 224
lr: 0.0001
lr_scheduler: reduce_on_plateau
n_shot: 1000
split_ratio: null
regions: null
vis_val: true
warmup: true
warmup_steps: 5
warmup_gamma: 10
min_lr: null
pretrained_model_path: not_required_due_to_terratorch
freeze_pretrained: true
data_path_128_10m: /Users/jja/Documents/02_EOFM/phi2FM/downstream/data/phileo-bench_roads.zarr
data_path_224_10m: /Users/jja/Documents/02_EOFM/phi2FM/downstream/data/phileo-bench_roads.zarr
data_path_224_30m: /Users/jja/Documents/02_EOFM/phi2FM/downstream/data/phileo-bench_roads.zarr
train_mode: train_test
downstream_model_path: null
data_path_inference_128: /Users/jja/Documents/02_EOFM/phi2FM/downstream/data/phileo-bench_roads.zarr
data_path_inference_224: /Users/jja/Documents/02_EOFM/phi2FM/downstream/data/phileo-bench_roads.zarr
output_path: /Users/jja/Documents/02_EOFM/phi2FM/downstream/output
data_parallel: false
device_ids:
- 0
pad_bands: 13
only_get_datasets: false
