
experiment_name: pretrain
downstream_task: pretrain
model_name: phisatnet_geoaware_xsmall   # **********************************
augmentations: True
batch_size: 12
model_device: cpu
generator_device: cpu
num_workers: 6
early_stop: 15
epochs: 50
input_channels: 8 # **********************************
input_size: 224 # **********************************
lr: 0.005
lr_scheduler: cosine_annealing
n_shot: null
split_ratio: 1.0
vis_val: True
warmup: True
warmup_steps: 5
warmup_gamma: null
min_lr: 0.000001
data_path: /home/ccollado/phileo_phisat2/MajorTOM/lmdb_patches_256_1536
train_mode: train_test                      # train_test, train_test_inference, inference, train_inference # **********************************
output_path: /home/ccollado/phisat2_foundation/models
data_parallel: False
device_ids: [0]
only_get_datasets: False
fixed_task: null