experiment_name: unet_myriad2_baseline/clouds
downstream_task: clouds
model_name: unet_myriad2_baseline
augmentations: true
batch_size: 16
model_device: cuda
generator_device: cuda
num_workers: 16
early_stop: 15
epochs: 200
input_channels: 8
output_channels: 5
input_size: 224
lr: 0.0001
lr_scheduler: reduce_on_plateau
n_shot:
- 50
- 100
- 500
- 1000
- 5000
split_ratio: null
regions: null
vis_val: true
warmup: true
warmup_steps: 5
warmup_gamma: 10
min_lr: null
pretrained_model_path: /home/gdaga/hydranet/experiments/distillation_production_20251113_001051/baseline/config_baseline/best_downstream_model.pt
freeze_pretrained: true
data_path_128_10m: /Data/phisatnet_clouds.zarr
data_path_224_10m: /Data/phisatnet_clouds.zarr
data_path_224_30m: /Data/phisatnet_clouds.zarr
train_mode: train_test
downstream_model_path: null
data_path_inference_128: /Data/phisatnet_clouds.zarr
data_path_inference_224: /Data/phisatnet_clouds.zarr
output_path: /Data/phi2FM_n_shot
data_parallel: false
device_ids:
- 0
wandb: true
patch_size: 224
shrink_val_set: 0.1
pad_bands: 8
only_get_datasets: false
