
experiment_name: phi2_phileo_precursor/clouds
downstream_task: clouds
model_name: phileo_precursor
augmentations: True
batch_size: 64
model_device: cuda
generator_device: cuda
num_workers: 16
early_stop: 15
epochs: 200
input_channels: 10
output_channels: 11
input_size: 64
lr: 0.0001
lr_scheduler: reduce_on_plateau
n_shot: [50, 100, 500, 1000, 5000] #null # ok?
split_ratio: 1
regions: null
vis_val: True
warmup: True
warmp_steps: 5
warmup_gamma: 10
min_lr: null
pretrained_model_path: /home/ccollado/phileo_NFS/phileo_data/newmodels/models/phileo-precursor_v09_e013.pt # **********************************
freeze_pretrained: True
data_path_128_10m: /Data/clouds_dataset/clouds_dataset.zarr
data_path_224_10m: /Data/clouds_dataset/clouds_dataset.zarr
data_path_224_30m: /Data/clouds_dataset/clouds_dataset.zarr
train_mode: train_test                      # train_test, train_test_inference, inference, train_inference
downstream_model_path: null
data_path_inference_128: /Data/clouds_dataset/clouds_dataset.zarr
data_path_inference_224: /Data/clouds_dataset/clouds_dataset.zarr
output_path: /Data/phi2FM_models
data_parallel: False
device_ids: [0]
pad_bands: 10 # 10 for all models, None for phisatnet, 13 for moco and dino
only_get_datasets: False
