experiment_name: phi2_SatMAE/burned_area_nshot100_frozen
downstream_task: burned_area
model_name: SatMAE
augmentations: true
batch_size: 32
model_device: cuda
generator_device: cuda
num_workers: 16
early_stop: 15
epochs: 200
input_channels: 10
output_channels: 4
input_size: 96
lr: 0.0001
lr_scheduler: reduce_on_plateau
n_shot: 100
split_ratio: null
regions: null
vis_val: true
warmup: true
warmup_steps: 5
warmup_gamma: 10
min_lr: null
pretrained_model_path: /lustre/projects/1001/gdaga/home/pretrained_weights/SatMAE_pretrain-vit-large-e199.pth
freeze_pretrained: true
data_path_128_10m: /lustre/projects/1001/gdaga/home/lpl_burned_area.zarr
data_path_224_10m: /lustre/projects/1001/gdaga/home/lpl_burned_area.zarr
data_path_224_30m: /lustre/projects/1001/gdaga/home/lpl_burned_area.zarr
train_mode: train_test
downstream_model_path: null
data_path_inference_128: /lustre/projects/1001/gdaga/home/lpl_burned_area.zarr
data_path_inference_224: /lustre/projects/1001/gdaga/home/lpl_burned_area.zarr
output_path: /lustre/projects/1001/gdaga/home/phi2FM_models
data_parallel: false
device_ids:
- 0
pad_bands: 10
only_get_datasets: false
